import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from './config.js';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const toast=(m)=>{const t=$('#adminToast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
const niceDate=(v)=>v?new Date(v).toLocaleString('en-BD',{dateStyle:'medium',timeStyle:'short'}):'—';
let products=[],categories=[],orders=[],content={},privateSettings={};

async function boot(){const {data:{session}}=await supabase.auth.getSession();if(session)await enterAdmin(session.user);}
async function enterAdmin(user){
  const {data,error}=await supabase.from('profiles').select('role').eq('id',user.id).maybeSingle();
  if(error||data?.role!=='admin'){await supabase.auth.signOut();$('#loginStatus').textContent='This account is not authorized as admin.';return;}
  $('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');await refreshAll();
}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);$('#loginStatus').textContent='Signing in…';const {data,error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error){$('#loginStatus').textContent=error.message;return}await enterAdmin(data.user)};
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};

$$('#adminNav button').forEach(b=>b.onclick=()=>{$$('#adminNav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(x=>x.classList.remove('active'));$(`#tab-${b.dataset.tab}`).classList.add('active');$('#tabTitle').textContent=b.textContent;if(b.dataset.tab==='assets')renderAssets();});

async function refreshAll(){
  const [p,c,o,ct,ps]=await Promise.all([
    supabase.from('products').select('*,categories(name,slug)').order('created_at',{ascending:false}),
    supabase.from('categories').select('*').order('sort_order'),
    supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(250),
    supabase.from('site_content').select('key,value'),
    supabase.from('private_settings').select('key,value')
  ]);
  products=p.data||[];categories=c.data||[];orders=o.data||[];content=Object.fromEntries((ct.data||[]).map(x=>[x.key,x.value]));privateSettings=Object.fromEntries((ps.data||[]).map(x=>[x.key,x.value]));
  renderDashboard();renderProducts();renderCategories();renderOrders();renderContent();renderSettings();
}
function renderDashboard(){
  const revenue=orders.filter(o=>!['cancelled','refunded'].includes(o.status)).reduce((s,o)=>s+Number(o.total||0),0);const pending=orders.filter(o=>['new','confirmed','processing'].includes(o.status)).length;
  $('#dashboardStats').innerHTML=[['Products',products.length],['Orders',orders.length],['Open orders',pending],['Order value',`৳${revenue.toLocaleString('en-BD')}`]].map(x=>`<div class="stat-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');
  $('#recentOrders').innerHTML=orders.slice(0,6).map(o=>`<div class="list-card"><div class="list-thumb" style="display:grid;place-items:center;background:#202027">#</div><div><h3>${esc(o.order_no)}</h3><p>${esc(o.customer_name)} · ${esc(o.phone)} · ${niceDate(o.created_at)}</p></div><strong>৳${Number(o.total||0).toLocaleString('en-BD')}</strong></div>`).join('')||'<p class="hint">No orders yet.</p>';
}
function renderProducts(filter=''){const q=filter.toLowerCase();const arr=products.filter(p=>!q||`${p.name} ${p.sku||''}`.toLowerCase().includes(q));$('#adminProducts').innerHTML=arr.map(p=>`<div class="list-card"><div>${p.images?.[0]?`<img src="${esc(p.images[0])}">`:'<div class="list-thumb" style="display:grid;place-items:center">👟</div>'}</div><div><h3>${esc(p.name)} ${!p.is_active?'<span style="color:#777">(hidden)</span>':''}</h3><p>${esc(p.categories?.name||'No category')} · ${esc(p.sku||'No SKU')} · ৳${Number(p.price||0).toLocaleString('en-BD')} · Stock ${p.stock??0}</p></div><div class="row-actions"><button data-edit-product="${p.id}">Edit</button><button class="delete" data-delete-product="${p.id}">Delete</button></div></div>`).join('')||'<div class="panel"><p class="hint">No products found.</p></div>';bindProductActions()}
$('#productSearch').oninput=e=>renderProducts(e.target.value);$('#addProductBtn').onclick=()=>openProductEditor();
function bindProductActions(){$$('[data-edit-product]').forEach(b=>b.onclick=()=>openProductEditor(products.find(p=>String(p.id)===b.dataset.editProduct)));$$('[data-delete-product]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this product?'))return;const {error}=await supabase.from('products').delete().eq('id',b.dataset.deleteProduct);if(error)return toast(error.message);toast('Product deleted');await refreshAll()})}
function openProductEditor(p={}){
  const catOptions=categories.map(c=>`<option value="${c.id}" ${String(p.category_id)===String(c.id)?'selected':''}>${esc(c.name)}</option>`).join('');
  $('#editorBody').innerHTML=`<form class="editor-form" id="productEditor"><h2>${p.id?'Edit':'Add'} product</h2><div class="grid2"><label>Name<input name="name" required value="${esc(p.name||'')}"></label><label>SKU<input name="sku" value="${esc(p.sku||'')}"></label><label>Category<select name="category_id"><option value="">No category</option>${catOptions}</select></label><label>Badge<input name="badge" placeholder="NEW / HOT / SALE" value="${esc(p.badge||'')}"></label><label>Price<input name="price" type="number" min="0" step=".01" required value="${p.price??''}"></label><label>Compare price<input name="compare_at_price" type="number" min="0" step=".01" value="${p.compare_at_price??''}"></label><label>Stock<input name="stock" type="number" min="0" value="${p.stock??0}"></label><label>Sort order<input name="sort_order" type="number" value="${p.sort_order??0}"></label></div><label>Short description<input name="short_description" value="${esc(p.short_description||'')}"></label><label>Description<textarea name="description" rows="4">${esc(p.description||'')}</textarea></label><div class="grid2"><label>Sizes (comma separated)<input name="sizes" value="${esc((p.sizes||[]).join(', '))}"></label><label>Colors (comma separated)<input name="colors" value="${esc((p.colors||[]).join(', '))}"></label></div><label>Tags (comma separated)<input name="tags" value="${esc((p.tags||[]).join(', '))}"></label><label>Image URLs (one per line)<textarea name="images" rows="4">${esc((p.images||[]).join('\n'))}</textarea></label><label>Upload product images<input type="file" name="image_files" accept="image/*" multiple></label><div class="checkrow"><label><input type="checkbox" name="featured" ${p.featured?'checked':''}> Featured</label><label><input type="checkbox" name="is_new" ${p.is_new?'checked':''}> New arrival</label><label><input type="checkbox" name="is_active" ${p.id?(p.is_active?'checked':''):'checked'}> Visible</label></div><button class="primary" type="submit">${p.id?'Save changes':'Create product'}</button><span class="status" id="editorStatus"></span></form>`;
  showEditor();$('#productEditor').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);$('#editorStatus').textContent='Saving…';try{let imgs=String(fd.get('images')||'').split('\n').map(x=>x.trim()).filter(Boolean);const files=fd.getAll('image_files').filter(f=>f?.size);if(files.length)imgs.push(...await uploadFiles(files,'products'));const payload={name:fd.get('name'),sku:fd.get('sku')||null,category_id:fd.get('category_id')||null,badge:fd.get('badge')||null,price:Number(fd.get('price')),compare_at_price:fd.get('compare_at_price')?Number(fd.get('compare_at_price')):null,stock:Number(fd.get('stock')||0),sort_order:Number(fd.get('sort_order')||0),short_description:fd.get('short_description')||null,description:fd.get('description')||null,sizes:splitComma(fd.get('sizes')),colors:splitComma(fd.get('colors')),tags:splitComma(fd.get('tags')),images:imgs,featured:fd.get('featured')==='on',is_new:fd.get('is_new')==='on',is_active:fd.get('is_active')==='on'};const r=p.id?await supabase.from('products').update(payload).eq('id',p.id):await supabase.from('products').insert(payload);if(r.error)throw r.error;hideEditor();toast('Product saved');await refreshAll()}catch(err){$('#editorStatus').textContent=err.message;}};
}
function splitComma(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}

function renderCategories(){
  $('#adminCategories').innerHTML=categories.map(c=>`<div class="list-card"><div>${c.image_url?`<img src="${esc(c.image_url)}">`:'<div class="list-thumb" style="display:grid;place-items:center">#</div>'}</div><div><h3>${esc(c.name)} ${!c.is_active?'<span style="color:#777">(hidden)</span>':''}</h3><p>/${esc(c.slug)} · Sort ${c.sort_order||0}</p></div><div class="row-actions"><button data-edit-cat="${c.id}">Edit</button><button class="delete" data-delete-cat="${c.id}">Delete</button></div></div>`).join('');
  $$('[data-edit-cat]').forEach(b=>b.onclick=()=>openCategoryEditor(categories.find(c=>String(c.id)===b.dataset.editCat)));$$('[data-delete-cat]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this category? Products will keep working but become uncategorized.'))return;const r=await supabase.from('categories').delete().eq('id',b.dataset.deleteCat);if(r.error)return toast(r.error.message);toast('Category deleted');await refreshAll()});
}
$('#addCategoryBtn').onclick=()=>openCategoryEditor();
function slugify(s){return String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function openCategoryEditor(c={}){$('#editorBody').innerHTML=`<form class="editor-form" id="catEditor"><h2>${c.id?'Edit':'Add'} category</h2><div class="grid2"><label>Name<input name="name" required value="${esc(c.name||'')}"></label><label>Slug<input name="slug" value="${esc(c.slug||'')}"></label><label>Sort order<input type="number" name="sort_order" value="${c.sort_order??0}"></label><label>Image URL<input name="image_url" value="${esc(c.image_url||'')}"></label></div><label>Description<textarea name="description" rows="3">${esc(c.description||'')}</textarea></label><label>Upload image<input type="file" name="image_file" accept="image/*"></label><div class="checkrow"><label><input type="checkbox" name="is_active" ${c.id?(c.is_active?'checked':''):'checked'}> Visible</label></div><button class="primary" type="submit">Save category</button><span id="editorStatus" class="status"></span></form>`;showEditor();$('#catEditor').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{let url=fd.get('image_url')||'';const f=fd.get('image_file');if(f?.size)url=(await uploadFiles([f],'categories'))[0];const name=fd.get('name');const payload={name,slug:fd.get('slug')||slugify(name),description:fd.get('description')||null,sort_order:Number(fd.get('sort_order')||0),image_url:url||null,is_active:fd.get('is_active')==='on'};const r=c.id?await supabase.from('categories').update(payload).eq('id',c.id):await supabase.from('categories').insert(payload);if(r.error)throw r.error;hideEditor();toast('Category saved');await refreshAll()}catch(err){$('#editorStatus').textContent=err.message}}};}

function renderContent(){const brand=content.brand||{},home=content.homepage||{},ui=content.ui||{};$('#contentFields').innerHTML=`<div class="content-group"><h3>Brand / announcement</h3><label>Store name<input name="brand_store_name" value="${esc(brand.store_name||'ALI FASHION')}"></label><label>Announcement bar<input name="announcement" value="${esc(brand.announcement||'')}"></label></div><div class="content-group"><h3>Homepage JSON</h3><p class="hint">Hero, navigation, section text, trust cards and footer links. Keep valid JSON.</p><textarea class="json-box" name="homepage_json">${esc(JSON.stringify(home,null,2))}</textarea></div><div class="content-group"><h3>UI labels JSON</h3><p class="hint">Buttons, cart messages, size/color labels and other microcopy.</p><textarea class="json-box" name="ui_json">${esc(JSON.stringify(ui,null,2))}</textarea></div>`;}
$('#contentForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{const homepage=JSON.parse(fd.get('homepage_json')||'{}'),ui=JSON.parse(fd.get('ui_json')||'{}');const brand={...(content.brand||{}),store_name:fd.get('brand_store_name'),announcement:fd.get('announcement')};await upsertContent('brand',brand);await upsertContent('homepage',homepage);await upsertContent('ui',ui);$('#contentStatus').textContent='Saved ✓';toast('Website content saved');await refreshAll()}catch(err){$('#contentStatus').textContent=`Error: ${err.message}`}};
async function upsertContent(key,value){const {error}=await supabase.from('site_content').upsert({key,value,updated_at:new Date().toISOString()});if(error)throw error;}

function renderSettings(){const s=content.settings||{};const f=$('#settingsForm');['store_name','currency','shipping_fee','free_shipping_over','phone','address'].forEach(k=>{if(f.elements[k])f.elements[k].value=s[k]??''});if(f.elements.owner_email)f.elements.owner_email.value=privateSettings.owner_email||'';}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const value={store_name:fd.get('store_name'),currency:fd.get('currency')||'BDT',shipping_fee:Number(fd.get('shipping_fee')||0),free_shipping_over:Number(fd.get('free_shipping_over')||0),phone:fd.get('phone'),address:fd.get('address')};try{await upsertContent('settings',value);const {error:pe}=await supabase.from('private_settings').upsert({key:'owner_email',value:String(fd.get('owner_email')||''),updated_at:new Date().toISOString()});if(pe)throw pe;privateSettings.owner_email=String(fd.get('owner_email')||'');$('#settingsStatus').textContent='Saved ✓';toast('Settings saved');content.settings=value}catch(err){$('#settingsStatus').textContent=err.message}};

function renderOrders(filter=''){const q=filter.toLowerCase();const arr=orders.filter(o=>!q||`${o.order_no} ${o.customer_name} ${o.email} ${o.phone}`.toLowerCase().includes(q));$('#ordersTable').innerHTML=`<table class="order-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${arr.map(o=>`<tr><td><strong>${esc(o.order_no)}</strong><br><span style="color:#666">${esc(o.city||'')}</span></td><td>${esc(o.customer_name)}<br><span style="color:#777">${esc(o.phone)} · ${esc(o.email)}</span><br><span style="color:#666">${esc(o.address)}</span></td><td class="order-items-mini">${(o.items||[]).map(i=>`${esc(i.name||'Product')} × ${i.qty}`).join('<br>')}</td><td><strong>৳${Number(o.total||0).toLocaleString('en-BD')}</strong></td><td><select data-order-status="${o.id}">${['new','confirmed','processing','shipped','delivered','cancelled','refunded'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${niceDate(o.created_at)}</td></tr>`).join('')}</tbody></table>`;$$('[data-order-status]').forEach(s=>s.onchange=async()=>{const r=await supabase.from('orders').update({status:s.value,updated_at:new Date().toISOString()}).eq('id',s.dataset.orderStatus);if(r.error)return toast(r.error.message);toast('Order status updated')});}
$('#orderSearch').oninput=e=>renderOrders(e.target.value);$('#refreshOrders').onclick=async()=>{await refreshAll();toast('Orders refreshed')};

async function uploadFiles(files,folder='media'){const urls=[];for(const file of files){const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');const path=`${folder}/${Date.now()}-${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('media').upload(path,file,{cacheControl:'3600',upsert:false});if(error)throw error;const {data}=supabase.storage.from('media').getPublicUrl(path);urls.push(data.publicUrl)}return urls;}
async function renderAssets(){const b=content.brand||{};$('#assetManager').innerHTML=`<div class="asset-grid"><div class="asset-card"><h3>Logo</h3><div class="asset-preview">${b.logo_url?`<img src="${esc(b.logo_url)}">`:'<span>Using GitHub default logo</span>'}</div><input id="logoUpload" type="file" accept="image/*"><button class="primary" id="saveLogo">Upload & use logo</button>${b.logo_url?'<button id="removeLogo">Use default logo</button>':''}</div><div class="asset-card"><h3>Favicon</h3><div class="asset-preview">${b.favicon_url?`<img src="${esc(b.favicon_url)}">`:'<span>Using GitHub default favicon</span>'}</div><input id="faviconUpload" type="file" accept="image/*"><button class="primary" id="saveFavicon">Upload & use favicon</button>${b.favicon_url?'<button id="removeFavicon">Use default favicon</button>':''}</div><div class="asset-card"><h3>General media</h3><div class="asset-preview"><span>Product & category images</span></div><input id="mediaUpload" type="file" accept="image/*" multiple><button class="primary" id="saveMedia">Upload files</button></div></div><h3 style="margin-top:25px">Storage media</h3><div class="media-list" id="mediaList"><span class="hint">Loading…</span></div>`;
  $('#saveLogo').onclick=async()=>assetUpload('logoUpload','logo_url','brand');$('#saveFavicon').onclick=async()=>assetUpload('faviconUpload','favicon_url','brand');$('#saveMedia').onclick=async()=>{const fs=[...$('#mediaUpload').files];if(!fs.length)return toast('Choose files first');try{await uploadFiles(fs,'media');toast('Media uploaded');await listMedia()}catch(e){toast(e.message)}};$('#removeLogo')?.addEventListener('click',()=>clearBrandAsset('logo_url'));$('#removeFavicon')?.addEventListener('click',()=>clearBrandAsset('favicon_url'));await listMedia();}
async function assetUpload(inputId,key,folder){const f=$(`#${inputId}`).files[0];if(!f)return toast('Choose an image first');try{const url=(await uploadFiles([f],folder))[0];const brand={...(content.brand||{}),[key]:url};await upsertContent('brand',brand);content.brand=brand;toast('Asset updated');renderAssets()}catch(e){toast(e.message)}}
async function clearBrandAsset(key){const brand={...(content.brand||{}),[key]:''};await upsertContent('brand',brand);content.brand=brand;toast('Default asset restored');renderAssets()}
async function listMedia(){const {data,error}=await supabase.storage.from('media').list('',{limit:100,sortBy:{column:'created_at',order:'desc'}});if(error){$('#mediaList').innerHTML=`<span class="hint">${esc(error.message)}</span>`;return}const folders=(data||[]).filter(x=>!x.id);let files=(data||[]).filter(x=>x.id).map(x=>({path:x.name,name:x.name}));for(const folder of folders){const r=await supabase.storage.from('media').list(folder.name,{limit:60,sortBy:{column:'created_at',order:'desc'}});files.push(...(r.data||[]).filter(x=>x.id).map(x=>({path:`${folder.name}/${x.name}`,name:x.name})))}$('#mediaList').innerHTML=files.slice(0,80).map(f=>{const {data}=supabase.storage.from('media').getPublicUrl(f.path);return `<div class="media-item"><img src="${esc(data.publicUrl)}" title="${esc(f.path)}"><button data-delete-media="${esc(f.path)}">✕</button></div>`}).join('')||'<span class="hint">No uploaded media yet.</span>';$$('[data-delete-media]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this file from storage? Existing product links may break.'))return;const r=await supabase.storage.from('media').remove([b.dataset.deleteMedia]);if(r.error)return toast(r.error.message);toast('Media deleted');listMedia()});}

function showEditor(){$('#editorModal').classList.add('show')}function hideEditor(){$('#editorModal').classList.remove('show')}$('#closeEditor').onclick=hideEditor;$('#editorModal').onclick=e=>{if(e.target.id==='editorModal')hideEditor()};
boot();
